### ISSUE TITLE
Options to say what to delete instead of what to keep

### ISSUE THREAD

**Issue by SenorSmartyPants** [shemanaev/jellyfin-plugin-media-cleaner#1]
I want to keep all videos by default and only delete the ones I specify. 

Could you add options to set it up that way? I'd rather not mark almost everything in my library as a favorite.

Thanks.

**Comment by shemanaev** [comment]
Could you elaborate? You want some button like "Favorite", except it would delete the item?

**Comment by blackwind** [comment]
Sounds like he wants a whitelist mode (`LocationsIncluded`). I'd like the same -- I want only one folder in my library to be affected, and I'd rather not add all the others to `LocationsExcluded` and risk oopsies if I add new folders to my library and forget to exclude them.

**Comment by shemanaev** [comment]
Yes, I see, this is valid concern. Published version **v.2.2.0.0** with this functionality.
