### ISSUE TITLE
[Bug]: Not deleting the whole folder

### ISSUE THREAD

**Issue by ibndiaye** [shemanaev/jellyfin-plugin-media-cleaner#20]
### What happened?

The media cleaner does not clear out the whole folder, as in the metadata images stay. 
The media(videos/season folders) get deleted but not the remaining posters.
Im running docker and gave jellyfin PUID and PGID 0.
Media Cleaner version: 2.6.1.0

![image](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/63436162/75a48be7-07af-47d0-b4ef-c32f6e74119c)

![image](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/63436162/b979e3bd-2cd0-4a83-a459-1a1ab2023c35)

**Comment by shemanaev** [comment]
The reason is simple: the plugin uses internal Jellyfin's delete function. AFAIK, it will delete only files recognized by Jellyfin. Otherwise, plugin can delete other movies that laid out next to each other without folders, for example. I'll think about some optional feature for those who understands consequences 😉

**Comment by ibndiaye** [comment]
Thanks for the explanation. Ill look into my folders  and look at whats causing this issue.

**Comment by TheSpyder** [comment]
Oddly I'm having the opposite problem. I started using `ytdl-sub` which keeps subscription info in the series folder where it downloads to.

Some of the last episodes from a channel were deleted this morning, and the entire folder is gone so now it's redownloading everything as a new subscription.

I'm about to look at the options to see if it can keep the subscription details somewhere else, but thought I'd come here first to see if it was a media cleaner bug. Clearly not!
