### ISSUE TITLE
[Feature]: delete only if the specified users has watched it

### ISSUE THREAD

**Issue by jumoog** [shemanaev/jellyfin-plugin-media-cleaner#21]
### Describe the feature you'd like added

For example, the movie must first be seen by person a and person b before it is deleted.

**Comment by shemanaev** [comment]
Have you tried to mark all users, except wanted in `Users->Ignore played state` setting?

**Comment by jumoog** [comment]
Here an example

Movies
**Keep for:** 60 Days
**Keep favorites:** No

**Ignore played state:**
- [ ] User K
- [ ] User L
- [x] User R
- [ ] User T

**Mode:** Include

Troubleshooting:
```
[Inf] MediaCleanupTask: (Movie) "Big Buck Bunny" will be deleted because expired for "K" (04/17/2023 17:33:45)
[Inf] MediaCleanupTask: (Movie) "Sintel" will be deleted because expired for "T" (04/21/2023 22:10:05)

```
User T never watched `Big Buck Bunny`
User K never watched `Sintel`

My goal is to have `Big Buck Bunny` deleted as soon as everyone but User R has seen it.

**Comment by shemanaev** [comment]
Oh, now I see the point. Added this to my to-do.

**Comment by shemanaev** [comment]
Update to the new version, there is now should be enough options ("Keep while not played by" + new list mode in Users section) for your scenario.
