### ISSUE TITLE
[Feature]: Option for plugin to erase watched media after x hours.

### ISSUE THREAD

**Issue by 2IkHLHB** [shemanaev/jellyfin-plugin-media-cleaner#22]
### Describe the feature you'd like added

It would be great if this plugin includes the option of having watched media deleted after the amount of hours we choose, instead of just having days as the only option.

**Comment by shemanaev** [comment]
The plugin isn't monitoring in real-time, but runs at specific intervals. You can, kinda, simulate desired behavior: set days to 0 and add trigger to "Played media cleanup" for desired amount of time.

**Comment by 2IkHLHB** [comment]
That actually works. Thanks.
