### ISSUE TITLE
Asking help for explanation of options

### ISSUE THREAD

**Issue by xiNeRoar** [shemanaev/jellyfin-plugin-media-cleaner#23]
### Describe the feature you'd like added

![image](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/66216186/b5e30dad-c7ce-459d-bdd5-949fd384787b)
I am having difficulties understanding the behaviour of the options....for example;
1. Keep while not played by
All users
All users have fully played the item

Does that mean keeping a single episode or keeping an entire series?
Does that mean keep the "episode/series" when no one is watching it?
If so, what does that mean by the description below: "All users have entirely played the item?

2. How will the option "delete after played" interact with "keep while not played by"?
If I have "deleted after played" set to "episode" and "keep while not played by" assigned to "any user," if I have one user played a single episode, will this plugin delete that specific episode? Or will it delete the whole series after the date I specify?

3. Under "Keep while not played by" > "Any user"
Does the description "At least one user have fully played item" mean a single episode or entire series? What does "item" refer to??

Sorry, I am so confused about the description and couldn't understand what the behaviour will be... I couldn't find any documentation that explains each option in detail, that's why I have to open an issue :(

**Comment by shemanaev** [comment]
1. This option's granularity depends on previous option "Delete after played". For example, with settings like on screenshot episodes watched by all users will be deleted (like, when show has 10 episodes, and only episode 5 was played by all users, then only episode 5 will be deleted).
2. Delete specific episode. These options directly connected.
3. Again, "item" is referring to option "Delete after played". It controls what will be an indivisible part. Like when it set to "season", all episodes of season has to be fully played, and so on.

Hope it makes clearer what is going on :)

**Comment by J-o-h-n-M** [comment]
When does media get deleted with setting 0? I would expect immediately. But that does not seem the case. Does it check every X hour or something?

**Comment by shemanaev** [comment]
It works via scheduled tasks. You can find «Played media cleanup» task in dashboard and customise its period. By default, I think, it runs every 24 hours.

**Comment by xiNeRoar** [comment]
I guess I am stupid on this :(, may I ask in this way;
is it achievable that;
1. if no one has played any episode in the series for 30 days, delete the whole series
2. if someone has played any episode in the series, keep the whole series for 30 days and extend it upon each play

**Comment by shemanaev** [comment]
No worries. This should be achievable with settings like below
![изображение](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/1058537/1b343d52-2f1f-44e8-b40b-a4f8f4a59342)

**Comment by xiNeRoar** [comment]
Thanks for your help again 😃

**Comment by xiNeRoar** [comment]
> No worries. This should be achievable with settings like below ![изображение](https://private-user-images.githubusercontent.com/1058537/312210971-1b343d52-2f1f-44e8-b40b-a4f8f4a59342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDAyMTksIm5iZiI6MTcyMzYzOTkxOSwicGF0aCI6Ii8xMDU4NTM3LzMxMjIxMDk3MS0xYjM0M2Q1Mi0yZjFmLTQ0ZTgtYjQwYi1hNGY4ZjRhNTkzNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMTI1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJmODIzZjc2OTcxOThjYmZmZDIzNzEwYTQ1ZjIwMTBmNTJhMzA0NGY5MWYwOWUyM2QxNTY3ODI3N2VlZjhmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.40U7i2ZBI9c_zOgSOfU4qybt1WL3dLlKx5kvdbL-I3E)

Sorry i have to reopen the issue because i found it not working and finally figure out why.
It only works when the amount of acknowledge player equal to 2 or 1, any amount larger than two user will not work at all even all condition are met.

**Comment by xiNeRoar** [comment]
> No worries. This should be achievable with settings like below ![изображение](https://private-user-images.githubusercontent.com/1058537/312210971-1b343d52-2f1f-44e8-b40b-a4f8f4a59342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDQwMDEsIm5iZiI6MTcyMzY0MzcwMSwicGF0aCI6Ii8xMDU4NTM3LzMxMjIxMDk3MS0xYjM0M2Q1Mi0yZjFmLTQ0ZTgtYjQwYi1hNGY4ZjRhNTkzNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMTM1NTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg3ZTA0YTMxYjhiOGVkNzliMGFmZTI2YjQ0MGRlOWFhMGU3NTkzZmE3ZjUwOGFmOWMxODg0ZjdhYmQ2MzY2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7H2XY5CJX6qcuR88Nzi0fGK8iJ7dG-eyaaGK2a-nJ9s)

Sorry i have to reopen the issue because i found it not working and finally figure out why. It will filter out all tasks when included user's that have no access to the selected library. Can this be further improve or fix?
