### ISSUE TITLE
[Feature Request]: Add The Option Of Deleting Audio

### ISSUE THREAD

**Issue by 2IkHLHB** [shemanaev/jellyfin-plugin-media-cleaner#26]
### Describe the feature you'd like added

I know this is a rather odd feature request but, please, hear me out.

Many people use Jellyfin to play audio podcasts. It would be nice to have the option on Media Cleaner to have said audios deleted automatically after played without any further human interaction.

Thank you for such an amazing plugin, and thank you in advance for your time. Good day.

Edit: Also, for people that want audiobooks automatically deleted.

**Comment by shemanaev** [comment]
Done in [v2.8.0.0](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/releases/tag/v2.8.0.0). Please report back any issues, as I personally don't use Jellyfin, neither for audio nor for audiobooks.

**Comment by 2IkHLHB** [comment]
> Done in [v2.8.0.0](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/releases/tag/v2.8.0.0). Please report back any issues, as I personally don't use Jellyfin, neither for audio nor for audiobooks.

Thank you for the update
I think I found a bug on this update. The new added options for audio and audiobooks are not being saved. I make the corresponding changes and press save. But when I return to the plugin's settings, I realized the changes were not saved.

**Comment by shemanaev** [comment]
Old settings being saved correctly? If so, maybe try to clear browser cache?
