### ISSUE TITLE
[Bug]: Status not supported

### ISSUE THREAD

**Issue by Dysta** [shemanaev/jellyfin-plugin-media-cleaner#27]
### What happened?

I installed the plugin from the official repositories and I'm unable to configure it since it was displayed as "Not supported" by Jellyfin in the plugins tab. 
![image](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/25008828/596f5ce8-ec3c-4693-880c-efcdeea989f1)

Plugin version: 2.8.0.0
Jellyfin version: 10.8.10

**Comment by shemanaev** [comment]
It was compiled for newer version of Jellyfin (10.8.11). Please update your server

**Comment by Dysta** [comment]
Done and it work
