### ISSUE TITLE
[Bug]: 2.8.0.0 Shemanaev Status: NotSupported

### ISSUE THREAD

**Issue by subcalc** [shemanaev/jellyfin-plugin-media-cleaner#28]
### What happened?

2.7.0.0 is working fine but it updates automatic and after a restart it is back on 2.8.0.0 

Troubleshoot info is from before the restart 
<img width="481" alt="fi 1" src="https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/58231219/405d4a5d-f72d-46b2-af7b-e36439a38a55">

after
<img width="242" alt="fi2" src="https://github.com/shemanaev/jellyfin-plugin-media-cleaner/assets/58231219/3134f2ae-5f9c-452b-9cfe-387a506254ff">

### Troubleshooting info

* Jellyfin version: 10.8.10
* Plugin version: 2.7.0.0
<details>
<summary>Configuration</summary>
<pre>
&lt;PluginConfiguration&gt;
  &lt;KeepMoviesFor&gt;7&lt;/KeepMoviesFor&gt;
  &lt;KeepPlayedMovies&gt;AnyUser&lt;/KeepPlayedMovies&gt;
  &lt;KeepFavoriteMovies&gt;AnyUser&lt;/KeepFavoriteMovies&gt;
  &lt;KeepEpisodesFor&gt;1&lt;/KeepEpisodesFor&gt;
  &lt;KeepPlayedEpisodes&gt;AnyUser&lt;/KeepPlayedEpisodes&gt;
  &lt;KeepFavoriteEpisodes&gt;DontKeep&lt;/KeepFavoriteEpisodes&gt;
  &lt;DeleteEpisodes&gt;Episode&lt;/DeleteEpisodes&gt;
  &lt;KeepVideosFor&gt;-1&lt;/KeepVideosFor&gt;
  &lt;KeepPlayedVideos&gt;AnyUser&lt;/KeepPlayedVideos&gt;
  &lt;KeepFavoriteVideos&gt;DontKeep&lt;/KeepFavoriteVideos&gt;
  &lt;UsersIgnorePlayed /&gt;
  &lt;UsersPlayedMode&gt;Ignore&lt;/UsersPlayedMode&gt;
  &lt;UsersIgnoreFavorited /&gt;
  &lt;UsersFavoritedMode&gt;Ignore&lt;/UsersFavoritedMode&gt;
  &lt;LocationsExcluded /&gt;
  &lt;LocationsMode&gt;Exclude&lt;/LocationsMode&gt;
  &lt;MarkAsUnplayed&gt;false&lt;/MarkAsUnplayed&gt;
&lt;/PluginConfiguration&gt;
</pre>
</details>
<details>
<summary>Log</summary>
<pre>
[Deb] MediaCleanupTask: UsersPlayedMode: Ignore
[Deb] MediaCleanupTask: UsersIgnorePlayed: 
[Deb] MediaCleanupTask: UsersFavoritedMode: Ignore
[Deb] MediaCleanupTask: UsersIgnoreFavorited: 
[Tra] JunkCollectors.MoviesJunkCollector: Collecting played items for 1 users started at 10/29/2023 20:36:53
[Deb] ItemsAdapter: &quot;The Wedding Veil Inspiration&quot; played by &quot;linda&quot; (10/29/2023 19:35:02)
[Deb] ItemsAdapter: &quot;The Wedding Veil Expectations&quot; played by &quot;linda&quot; (10/29/2023 19:34:59)
[Deb] ItemsAdapter: &quot;The Wedding Veil Journey&quot; played by &quot;linda&quot; (10/29/2023 19:34:55)
[Deb] JunkCollectors.MoviesJunkCollector: Filters order: Expired, Favorites, Locations
[Deb] JunkCollectors.MoviesJunkCollector: 3 items before filtering
[Tra] JunkCollectors.MoviesJunkCollector: &quot;The Wedding Veil Inspiration&quot; filtered by Expired
[Tra] JunkCollectors.MoviesJunkCollector: &quot;The Wedding Veil Expectations&quot; filtered by Expired
[Tra] JunkCollectors.MoviesJunkCollector: &quot;The Wedding Veil Journey&quot; filtered by Expired
[Deb] JunkCollectors.MoviesJunkCollector: 0 items after filtering
[Tra] JunkCollectors.MoviesJunkCollector: Collecting finished at 10/29/2023 20:36:53
[Tra] JunkCollectors.SeriesJunkCollector: Collecting played items for 1 users started at 10/29/2023 20:36:53
[Deb] ItemsAdapter: &quot;It Came From Michoac&#225;n&quot; played by &quot;linda&quot; (10/28/2023 20:18:55)
[Deb] JunkCollectors.SeriesJunkCollector: Filters order: Expired, Favorites, Locations, Series
[Deb] JunkCollectors.SeriesJunkCollector: 1 items before filtering
[Deb] JunkCollectors.SeriesJunkCollector: 1 items after filtering
[Tra] JunkCollectors.SeriesJunkCollector: Collecting finished at 10/29/2023 20:36:54
[Inf] MediaCleanupTask: (Episode) &quot;It Came From Michoac&#225;n&quot; will be deleted because expired for: linda (28-10-2023 20:18:55)
</pre>
</details>

**Comment by frozenbanana97** [comment]
I'm having the same issue, I tried removing the data from Jellyfins config directory and reinstall Media Cleaner but the same issue occurred.

I just disabled my plugin update task and installed a previous version for the time being and it seems to be working.

**Comment by shemanaev** [comment]
Please update Jellyfin to the latest version.

**Comment by subcalc** [comment]
> Please update Jellyfin to the latest version.

Solved
