### ISSUE TITLE
[Feature]: Can you make the latest version of the plugin support the old version number of Jellyfin?

### ISSUE THREAD

**Issue by shanyan-wcx** [shemanaev/jellyfin-plugin-media-cleaner#30]
### Describe the feature you'd like added

I am using nyamisaka/jellyfin: latest because this image includes graphics card drivers, FFmpeg, and Chinese fonts. Its version number is behind the official version, at 10.8.10, but its functionality is ahead of the official version. The media cleaner is displayed as unsupported on this version number.

**Comment by shemanaev** [comment]
I'd rather not. But you can install specific previous version via Plugins Catalog until the fork you use catches up.

**Comment by shanyan-wcx** [comment]
But installing the old version will be automatically updated.

**Comment by shemanaev** [comment]
Well, there's flag "autoUpdate" in meta.json of plugin, but it seems broken in Jellyfin...
And I really don't want to downgrade dependencies as they're marked unsafe.
So, there's two options right now:
1. Compile latest version of plugin with specific modifications by yourself and replace files
2. I can compile it for you, if you don't mind picking file from random guy 😄

**Comment by shanyan-wcx** [comment]
Please compile it for me.

**Comment by shemanaev** [comment]
Here you go: 
[MediaCleaner_2.9.0.0_abi_10.8.4.zip](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/files/13466083/MediaCleaner_2.9.0.0_abi_10.8.4.zip)

**Comment by shanyan-wcx** [comment]
Thank you.
