### ISSUE TITLE
Are favourited series and collections ignored? 

### ISSUE THREAD

**Issue by sym0nd0** [shemanaev/jellyfin-plugin-media-cleaner#32]
Sorry, probably a stupid question. If a user favourites a collection of movies or an entire series of a TV show would those be ignored by Media Cleaner or would every episode or movie need to be individually favourited?

Thanks!

**Comment by shemanaev** [comment]
Not stupid at all. 

For series it is based on granularity, e.g. if you choose to delete every episode, favorites filter will lookup in next order: episode -> season -> series. If you choose to delete per season: season -> series.

Collections currently aren't handled in any way, so for movies only way is to mark individually. (I probably add this to my plan).
