### ISSUE TITLE
10.8.4 click users and locations without response, or even get stuck

### ISSUE THREAD

**Issue by shanyan-wcx** [shemanaev/jellyfin-plugin-media-cleaner#4]

**Comment by shemanaev** [comment]
Please, share client system info where the issue is reproduced:
- platform (OS and its version)
- browser and its version
- installed extensions

**Comment by shanyan-wcx** [comment]
Windows 11 22622.590

Microsoft Edge 105.0.1343.27

AudioDB10.8.4.0
状态： Active
Bangumi1.4.18.0
状态： Active
Bookshelf9.0.0.0
状态： Active
Cover Art Archive7.0.0.0
状态： Active
Fanart10.0.0.0
状态： Active
Intro Skipper0.1.6.0
状态： Active
Kodi Sync Queue9.0.0.0
状态： Active
MaxSubtitle10.8.0.0
状态： Active
Merge Versions10.8.0.1
状态： Active
MusicBrainz10.8.4.0
状态： Active
OMDb10.8.4.0
状态： Active
OPDS Feed4.0.0.0
状态： Active
Open Subtitles18.0.0.0
状态： Active
OpenDouban10.8.0.0
状态： Active
Playback Reporting13.0.0.0
状态： Active
Reports15.0.0.0
状态： Active
Session Cleaner2.0.0.0
状态： Active
SkinManager1.5.0.0
状态： Active
Studio Images10.8.4.0
状态： Active
TMDb10.8.4.0
状态： Active
TMDb Box Sets10.0.0.0
状态： Active
Theme Songs10.8.0.1
状态： Active
Trakt20.0.0.0
状态： Active

**Comment by shemanaev** [comment]
Could you check is the tabs working fine in "Playback Reporting" plugin?
Also, what browser extensions do you have active?

**Comment by shanyan-wcx** [comment]
The label of playback reporting works normally

Cookie-Editor
GUID Generator
YT 4K Downloader
uBlock Origin
一键式视频下载器
彩云小译 - 网页翻译插件
暴力猴
CL1024
Chevereto download button
Clean All - History & Cache Cleaner
Convertio
Daxab Ultimate
Dmooji 弹幕君 - YouTube弹幕助手
Enhanced GitHub
Get CRX
GitZip for github
Noptcha: ReCAPTCHA & hCAPTCHA Solver
OctoLinker
Octotree - GitHub code tree
PT Plugin Plus
RSI Companion
Real Debrid Download Manager
Sourcegraph
Star Citizen Bulk XPLORer
Star Citizen CCU Game
Star Citizen Hangar XPLORer
Stream Recorder - download HLS as MP4
Super Netflix
迅雷下载支持

**Comment by shanyan-wcx** [comment]
It seems that it has nothing to do with the browser extension, because this problem still exists after I turn off all the extensions, and clicking users and locations in jellyfin media player will lead to a black screen

**Comment by shemanaev** [comment]
Oh, so issue reproduces in [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player) actually?

**Comment by shanyan-wcx** [comment]
There are problems with both the browser and the media player

**Comment by shemanaev** [comment]
Try this build [MediaCleaner.zip](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/files/9487349/MediaCleaner.zip) (don't forget to reboot server).

**Comment by shanyan-wcx** [comment]
This can work normally

**Comment by shemanaev** [comment]
Version with fix has been released. It will update as usual.
