### ISSUE TITLE
Question regarding recent update.

### ISSUE THREAD

**Issue by JamsRepos** [shemanaev/jellyfin-plugin-media-cleaner#49]
Hey,

Thanks for the update - just to confirm, was this due to irregular crashes occuring or just general updates to keep in-line with the Jellyfin version? As I had a few crashes today and I am not sure whether it was caused by this or not, so just trying to rule it out.

Either way, thank you for the update!

**Comment by shemanaev** [comment]
Hi, this update was to make it compatible with 10.9. Do you experience Jellyfin crashes or plugin only? Plugins shouldn't crash whole server, but anyways if you have related logs I will appreciate it.

**Comment by JamsRepos** [comment]
Was just trying to rule out if you were making changes to fix things. It just seemed the server was still running but the front end wouldn't work. 

It's not happened since I updated a bunch of plugins and removed ones I didn't need. SIMKL at the start of 10.9 was crashing servers so plugins can definitely contribute. 

I'll close this though and we will see if it happens again and I'll sort through the logs deeper to see the cause. 

Thanks!
