### ISSUE TITLE
[Bug]: Media not getting deleted

### ISSUE THREAD

**Issue by lyonelzd** [shemanaev/jellyfin-plugin-media-cleaner#50]
### What happened?

I ran the task manually but episodes are not getting deleted, not sure what is going on.

### Troubleshooting info

* Jellyfin version: 10.9.1
* Plugin version: 2.16.0.0
<details>
<summary>Configuration</summary>
<pre>
&lt;PluginConfiguration&gt;
  &lt;KeepMoviesFor&gt;-1&lt;/KeepMoviesFor&gt;
  &lt;KeepMoviesNotPlayedFor&gt;-1&lt;/KeepMoviesNotPlayedFor&gt;
  &lt;KeepPlayedMovies&gt;AnyUser&lt;/KeepPlayedMovies&gt;
  &lt;KeepFavoriteMovies&gt;AnyUser&lt;/KeepFavoriteMovies&gt;
  &lt;KeepEpisodesFor&gt;-1&lt;/KeepEpisodesFor&gt;
  &lt;KeepEpisodesNotPlayedFor&gt;-1&lt;/KeepEpisodesNotPlayedFor&gt;
  &lt;KeepPlayedEpisodes&gt;AnyUser&lt;/KeepPlayedEpisodes&gt;
  &lt;KeepFavoriteEpisodes&gt;AnyUser&lt;/KeepFavoriteEpisodes&gt;
  &lt;DeleteEpisodes&gt;Season&lt;/DeleteEpisodes&gt;
  &lt;KeepVideosFor&gt;-1&lt;/KeepVideosFor&gt;
  &lt;KeepVideosNotPlayedFor&gt;-1&lt;/KeepVideosNotPlayedFor&gt;
  &lt;KeepPlayedVideos&gt;AnyUser&lt;/KeepPlayedVideos&gt;
  &lt;KeepFavoriteVideos&gt;AnyUser&lt;/KeepFavoriteVideos&gt;
  &lt;KeepAudioFor&gt;-1&lt;/KeepAudioFor&gt;
  &lt;KeepAudioNotPlayedFor&gt;-1&lt;/KeepAudioNotPlayedFor&gt;
  &lt;KeepPlayedAudio&gt;AnyUser&lt;/KeepPlayedAudio&gt;
  &lt;KeepFavoriteAudio&gt;AnyUser&lt;/KeepFavoriteAudio&gt;
  &lt;KeepAudioBooksFor&gt;-1&lt;/KeepAudioBooksFor&gt;
  &lt;KeepAudioBooksNotPlayedFor&gt;-1&lt;/KeepAudioBooksNotPlayedFor&gt;
  &lt;KeepPlayedAudioBooks&gt;AnyUser&lt;/KeepPlayedAudioBooks&gt;
  &lt;KeepFavoriteAudioBooks&gt;AnyUser&lt;/KeepFavoriteAudioBooks&gt;
  &lt;UsersIgnorePlayed /&gt;
  &lt;UsersPlayedMode&gt;Ignore&lt;/UsersPlayedMode&gt;
  &lt;UsersIgnoreFavorited /&gt;
  &lt;UsersFavoritedMode&gt;Ignore&lt;/UsersFavoritedMode&gt;
  &lt;LocationsExcluded /&gt;
  &lt;LocationsMode&gt;Exclude&lt;/LocationsMode&gt;
  &lt;MarkAsUnplayed&gt;false&lt;/MarkAsUnplayed&gt;
&lt;/PluginConfiguration&gt;
</pre>
</details>
<details>
<summary>Log</summary>
<pre>
[Deb] MediaCleanupTask: UsersPlayedMode: Ignore
[Deb] MediaCleanupTask: UsersIgnorePlayed: 
[Deb] MediaCleanupTask: UsersFavoritedMode: Ignore
[Deb] MediaCleanupTask: UsersIgnoreFavorited: 
</pre>
</details>

**Comment by shemanaev** [comment]
You need to configure plugin. By default it set to "-1", i.e. "Don't touch anything"

**Comment by lyonelzd** [comment]
> You need to configure plugin. By default it set to "-1", i.e. "Don't touch anything"

OH...oops lol. I misunderstood it, I thought it meant "I don't care how many days just delete it".
It works now. Sorry about that, thank you for the plugin!
