### ISSUE TITLE
[Bug]: Keep not played for X days setting not respsected

### ISSUE THREAD

**Issue by xiNeRoar** [shemanaev/jellyfin-plugin-media-cleaner#54]
### What happened?

I have tried to configure keep not played for X days from 1 to 30, the plugin will keep everything since someone has watched it no matter how long it was

### Troubleshooting info

This is the only occurrence of the show watch which is 2 months ago;
![image](https://github.com/user-attachments/assets/d60907f8-ef63-4ab9-8e4a-5a5622f7b0af)
This is my setting;
![image](https://github.com/user-attachments/assets/af136660-db64-4768-a665-938d3d5809ba)

![image](https://github.com/user-attachments/assets/afef25b2-17f3-40ce-8228-dc5fe029d5df)
![image](https://github.com/user-attachments/assets/7193153d-1614-4951-99b4-d9354b836841)
![image](https://github.com/user-attachments/assets/484b8884-79bf-4720-b5a0-17d68de8dd77)
![image](https://github.com/user-attachments/assets/7a2ba820-9815-4a12-ab4a-179cba5616e1)
This is the original log;
[log.txt](https://github.com/user-attachments/files/16625262/log.txt)

**Comment by shemanaev** [comment]
Hi, will setting like "don't count item as played after X days of last play" solve this problem?

For example: the value is set to 10, the last time the TV show episode was watched on January 10th, so after January 20th this play will not be counted.

**Comment by xiNeRoar** [comment]
> Hi, will setting like "don't count item as played after X days of last play" solve this problem?
> 
> For example: the value is set to 10, the last time the TV show episode was watched on January 10th, so after January 20th this play will not be counted.

yes I think so, but I think how this setting interact with "keep not played episode for x days" need to be treated or documented carefully?

**Comment by shemanaev** [comment]
> yes I think so, but I think how this setting interact with "keep not played episode for x days" need to be treated or documented carefully? 

Could you try [this build](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/actions/runs/10546288983/artifacts/1851619742)?


> Also, as the original purpose of this plugin is to "delete played media files after specified amount of time", I guess re-group the options into two main category will help user better understand how they should setup the plugin?
> 
> e.g.;
> 
>     1. Delete media after played
>        Time - [ ] Days
>        Trigger Scope - [ ] Single Episode / Whole Season / Whole Series
>        Delete Scope - [ ] Single Episode / Whole Season / Whole Series
>        Monitor - [ ] All User / Any User / Any User(Latest Playback)
> 
>     2. Delete media after not being played
>        Time - [ ] Days
>        Trigger Scope - [ ] Single Episode / Whole Season / Whole Series
>        Delete Scope - [ ] Single Episode / Whole Season / Whole Series
>        Monitor - [ ] All User / Any User / Any User(Latest Playback)

That's a good suggestion, I will look into it. Current UX isn't great for sure, it started as simple plugin for my needs and grows with features.

**Comment by xiNeRoar** [comment]
> > yes I think so, but I think how this setting interact with "keep not played episode for x days" need to be treated or documented carefully?
> 
> Could you try [this build](https://github.com/shemanaev/jellyfin-plugin-media-cleaner/actions/runs/10546288983/artifacts/1851619742)?
> 
> > Also, as the original purpose of this plugin is to "delete played media files after specified amount of time", I guess re-group the options into two main category will help user better understand how they should setup the plugin?
> > e.g.;
> > ```
> > 1. Delete media after played
> >    Time - [ ] Days
> >    Trigger Scope - [ ] Single Episode / Whole Season / Whole Series
> >    Delete Scope - [ ] Single Episode / Whole Season / Whole Series
> >    Monitor - [ ] All User / Any User / Any User(Latest Playback)
> > 
> > 2. Delete media after not being played
> >    Time - [ ] Days
> >    Trigger Scope - [ ] Single Episode / Whole Season / Whole Series
> >    Delete Scope - [ ] Single Episode / Whole Season / Whole Series
> >    Monitor - [ ] All User / Any User / Any User(Latest Playback)
> > ```
> 
> That's a good suggestion, I will look into it. Current UX isn't great for sure, it started as simple plugin for my needs and grows with features.

I am more willing to try it out but I am not so familiar with the file, how can I use it?

**Comment by shemanaev** [comment]
> I am more than willing to try it out but I am not so familiar with the file, how can I use it?

Just unzip it, replace original dll (`<Jellyfin config folder>/plugins/Media Cleaner_2.17.0.0`) and restart server.

**Comment by xiNeRoar** [comment]
I tried and here is the log;
[log.txt](https://github.com/user-attachments/files/16740710/log.txt)
the item being tested is "鬼灭之刃" season 1, it only played once on 07/23/2023 but still endup the cleanup task doesn't list out this season to delete
![image](https://github.com/user-attachments/assets/c1f2b079-b84c-4b06-b48b-ed2920694246)

**Comment by shemanaev** [comment]
> I tried and here is the log; [log.txt](https://github.com/user-attachments/files/16740710/log.txt) the item being tested is "鬼灭之刃" season 1 and 4, they only played once on 07/23/2023 but still endup the cleanup task doesn't list out this season to delete ![image](https://private-user-images.githubusercontent.com/66216186/361239443-c1f2b079-b84c-4b06-b48b-ed2920694246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTc3MDEsIm5iZiI6MTcyNDU5NzQwMSwicGF0aCI6Ii82NjIxNjE4Ni8zNjEyMzk0NDMtYzFmMmIwNzktYjg0Yy00YjA2LWI0OGItZWQyOTIwNjk0MjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE0NTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMDRhYjRiYzU2MmY0MjgyNzkxMDg3ZWYzNDU3MDAyNWYwODg4YWM1YjBmY2Q5MTBiMTI5Y2VhNjg0MzdjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ym0RxgtfLPZyY3BoOb8aP5LJw2xKC1new3lw2cGnE3M)

You need to configure the new option first
![изображение](https://github.com/user-attachments/assets/2f12536e-925f-4507-aebb-1b0975438ffc)

**Comment by xiNeRoar** [comment]
thanks it seems working! :) but i still need to observe it for couple days to ensure it works as intended
![image](https://github.com/user-attachments/assets/d43a9f98-c92c-42e9-a107-057fa979608e)
![image](https://github.com/user-attachments/assets/908cc4fc-fb6b-450a-a555-c5dcc2533e40)
I was trying to configure it to only acknowledge current day's watch state. If someone watch it today, extend it for another 30 days. If no one watch it, it will count down 30 days until being deleted. I will try to shorten the period from 30 days to 2 or 3 days and observe how it operate and report here :D

**Comment by shemanaev** [comment]
Value "30" should do it. Like "if no one watched in last 30 days".

> observe how it operate and report here :D

I will keep an eye on it 😉

**Comment by NicolaSmaniotto** [comment]
Hi, just want to say that I'm testing this new build and everything seems to work as expected.

Also, it fixes the thing I mentioned in https://github.com/shemanaev/jellyfin-plugin-media-cleaner/issues/39#issuecomment-1983138196, because if someone drops a series its partial plays are now ignored after X days, and it is then removed because nobody watched it.

With these changes the plugin does pretty much everything I wanted it to, thanks!

**Comment by shemanaev** [comment]
Merged into mainline
