### ISSUE TITLE
Is this plugin right for me?

### ISSUE THREAD

**Issue by thereddestdog** [shemanaev/jellyfin-plugin-media-cleaner#59]
Hi, I've been in search of a replacement of [sonarr-episode-trimmer](https://gitlab.com/spoatacus/sonarr-episode-trimmer) ever since upgrading Sonarr to v4. 

Basically, it works on a by-series basis, where I just say what TV series I want to have a maximum number of episodes, regardless of watched state.

Can Media Cleaner behave the same way for me? It looks like this plugin applies the same criteria to all episodes or movies

Thanks!

**Comment by shemanaev** [comment]
Hi,

Unfortunately, it won't meet your requirements, as the rules are applied
globally and can't be customized for individual shows. I don't anticipate
this changing anytime soon, sorry.

сб, 19 окт. 2024 г., 10:20 thereddestdog ***@***.***>:

**Comment by thereddestdog** [comment]
OK thanks for your reply
