### ISSUE TITLE
[Feature]: set log level

### ISSUE THREAD

**Issue by NicolaSmaniotto** [shemanaev/jellyfin-plugin-media-cleaner#60]
### Describe the feature you'd like added

I'd like to select which log level the plugin writes in the troubleshooting page.

### Additional context

With many users, the plugin prints many lines of type `[Tra]`, which are useful for troubleshooting but create a lot of noise when trying to determine what it is trying to do. If there was an option to hide those lines the output would be much easier to read.

For context, the plugin on my server currently prints ~23k lines, of which ~22k are `[Tra]`.

**Comment by shemanaev** [comment]
Here you go.
