### ISSUE TITLE
Question - Redownloaded media

### ISSUE THREAD

**Issue by aleksasiriski** [shemanaev/jellyfin-plugin-media-cleaner#8]
So, some media is watched and is deleted after X days, what happens when that same media gets downloaded again?

If it instantly gets deleted again I think that's wrong. I'll probably later look at the code and add some PRs but my question is now: Does it use some database that it clears after successfuly deleting something?

**Comment by shemanaev** [comment]
> If it instantly gets deleted again I think that's wrong.

Correct, it'll be deleted on next scheduled task run.

> Does it use some database that it clears after successfuly deleting something?

No, plugin uses [Played](https://github.com/jellyfin/jellyfin/blob/f3ac9ba4659d58f7bfe1bd006fbea1f68f86b73b/MediaBrowser.Controller/Entities/UserItemData.cs#L84) and [LastPlayedDate](https://github.com/jellyfin/jellyfin/blob/f3ac9ba4659d58f7bfe1bd006fbea1f68f86b73b/MediaBrowser.Controller/Entities/UserItemData.cs#L78) fields Jellyfin is in charge of.

> I'll probably later look at the code and add some PRs

I don't mind the option to reset watch state upon deletion. So when media downloaded again it'll be marked as unwatched, which is kinda makes sense.

**Comment by aleksasiriski** [comment]
I'll be working on the fork or another plugin of my own these next days since I need this to work better.

Now, if you change the license to a [non cuck](https://lukesmith.xyz/articles/why-i-use-the-gpl-and-not-cuck-licenses/) one I'll add the PRs if not I'll make a seperate plugin. Thanks for understanding.
