### ISSUE TITLE
[Feature]: test mode

### ISSUE THREAD

**Issue by SenorSmartyPants** [shemanaev/jellyfin-plugin-media-cleaner#9]
### Describe the feature you'd like added

Option to set the plugin to test mode where it won't delete anything but it will log what it would delete. This would be helpful to confirm it is configured how a user wants it.

**Comment by shemanaev** [comment]
This is exactly what "Troubleshooting" tab for in settings. You can experiment with settings, and it'll show decisions log every time you get there. And if you want to be extra cautious, disable scheduled task temporarily.

**Comment by shemanaev** [comment]
I've added toggle to view rendered log into troubleshooting tab.
Feel free to reopen if you think it's not sufficient.
